import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from "./navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="flex-0">
            <Navbar />
          </div>
          <div className='flex-1 p-8 overflow-hidden'>{children}</div>
        </div>
      </body>
    </html>
  );
}
